"""
hull_sequence_classifier.py
============================
Transformer-based sequential hull classifier.

Replaces the MLP in LearnedHullClassifier with a causal Transformer
that processes the full trajectory history before labeling each step.

Key design decisions:
  - Input:   [state | action | delta_state] per step  → rich trajectory encoding
  - Model:   Causal Transformer (GPT-style masking) so step t only sees t' <= t
  - Output:  Per-step soft probability + epistemic uncertainty (MC Dropout)
  - Labels:  Generated by any exact oracle (PostEpisodeHullMonitor, etc.)
  - Training: Online — label buffer fills as episodes complete, model retrains
              periodically on batched trajectory windows

Interface: identical to LearnedHullClassifier — drop-in replacement.
    monitor = SequentialHullClassifier(xDim, uDim, action_bounds)
    result  = monitor.process(record)   # HullResult with soft probs + uncertainty
"""

from __future__ import annotations

import math
from collections import deque
from dataclasses import dataclass, field
from typing import List, Optional, Tuple

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# ── Import shared types from hull_monitors ────────────────────────────────────
# (copy-paste EpisodeRecord / HullResult here if not importing from that file)
try:
    from hull_monitors import (
        EpisodeRecord, HullResult, PostEpisodeHullMonitor, _scan_episode
    )
except ImportError:
    # Standalone fallback — define minimal versions
    from dataclasses import dataclass
    import numpy as np

    @dataclass
    class EpisodeRecord:
        states:  np.ndarray
        actions: np.ndarray
        rewards: np.ndarray
        ep_id:   int = 0

        @property
        def T(self): return len(self.actions)

    @dataclass
    class HullResult:
        in_hull_mask:    np.ndarray
        first_hull_step: Optional[int]
        is_valid_target: bool
        source:          str = "unknown"

        @property
        def hull_reached(self): return self.first_hull_step is not None

        def relabel_rewards(self, rewards, hull_reward):
            if not self.hull_reached: return rewards.copy()
            out = rewards.copy()
            out[self.in_hull_mask] = hull_reward
            return out


# ══════════════════════════════════════════════════════════════════════════════
#  EXTENDED HULL RESULT  (adds uncertainty fields)
# ══════════════════════════════════════════════════════════════════════════════

@dataclass
class SequentialHullResult(HullResult):
    """
    HullResult extended with per-step probability and uncertainty estimates.

    probs:       (T,)  — mean predicted P(in_hull) at each step
    uncertainty: (T,)  — epistemic uncertainty (std over MC Dropout samples)
    confident_mask: (T,) — steps where uncertainty < threshold
    """
    probs:           np.ndarray = field(default_factory=lambda: np.array([]))
    uncertainty:     np.ndarray = field(default_factory=lambda: np.array([]))
    confident_mask:  np.ndarray = field(default_factory=lambda: np.array([], dtype=bool))

    def relabel_rewards_confident(self, rewards: np.ndarray,
                                   hull_reward: float) -> np.ndarray:
        """Only relabel steps where the model is confident."""
        if not self.hull_reached:
            return rewards.copy()
        out = rewards.copy()
        confident_hull = self.in_hull_mask & self.confident_mask
        out[confident_hull] = hull_reward
        return out


# ══════════════════════════════════════════════════════════════════════════════
#  INPUT ENCODER
# ══════════════════════════════════════════════════════════════════════════════

class TrajectoryInputEncoder(nn.Module):
    """
    Encodes per-step inputs into a fixed-size token embedding.

    For each step t, the token is the concatenation of:
      - state[t]                    (xDim)
      - action[t]                   (uDim)
      - delta_state[t] = s[t]-s[t-1] (xDim, zero for t=0)

    All features are layer-normed before projection.
    """

    def __init__(self, xDim: int, uDim: int, d_model: int):
        super().__init__()
        self.xDim    = xDim
        self.uDim    = uDim
        in_dim       = xDim + uDim + xDim      # state + action + delta
        self.norm_in = nn.LayerNorm(in_dim)
        self.proj    = nn.Linear(in_dim, d_model)
        self.act     = nn.GELU()

    def forward(self, states: torch.Tensor, actions: torch.Tensor) -> torch.Tensor:
        """
        Args:
            states:  (B, T+1, xDim)
            actions: (B, T,   uDim)
        Returns:
            tokens:  (B, T, d_model)
        """
        # delta_state[t] = state[t+1] - state[t]  (next - current)
        delta = states[:, 1:, :] - states[:, :-1, :]    # (B, T, xDim)

        # Current state at each step
        s_t = states[:, :-1, :]                          # (B, T, xDim)

        x   = torch.cat([s_t, actions, delta], dim=-1)  # (B, T, in_dim)
        x   = self.norm_in(x)
        return self.act(self.proj(x))                    # (B, T, d_model)


# ══════════════════════════════════════════════════════════════════════════════
#  POSITIONAL ENCODING
# ══════════════════════════════════════════════════════════════════════════════

class SinusoidalPositionalEncoding(nn.Module):
    """Standard sinusoidal PE, supports variable sequence length."""

    def __init__(self, d_model: int, max_len: int = 2048, dropout: float = 0.1):
        super().__init__()
        self.dropout = nn.Dropout(dropout)

        pe  = torch.zeros(max_len, d_model)
        pos = torch.arange(max_len).unsqueeze(1).float()
        div = torch.exp(torch.arange(0, d_model, 2).float()
                        * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(pos * div)
        pe[:, 1::2] = torch.cos(pos * div)
        self.register_buffer("pe", pe.unsqueeze(0))   # (1, max_len, d_model)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """x: (B, T, d_model)"""
        return self.dropout(x + self.pe[:, :x.size(1), :])


# ══════════════════════════════════════════════════════════════════════════════
#  CAUSAL TRANSFORMER BACKBONE
# ══════════════════════════════════════════════════════════════════════════════

class CausalTransformerBackbone(nn.Module):
    """
    GPT-style causal Transformer.
    Each position t attends only to positions <= t (lower-triangular mask).
    This ensures the label at step t is predicted from trajectory[:t] only —
    no lookahead, consistent with online inference.

    Uses pre-norm (LayerNorm before attention/FFN) for training stability.
    MC Dropout is applied at every layer — keep model.train() during inference
    to get uncertainty estimates.
    """

    def __init__(
        self,
        d_model:   int = 128,
        nhead:     int = 4,
        num_layers: int = 3,
        dim_ff:    int = 256,
        dropout:   float = 0.1,
        max_len:   int = 1024,
    ):
        super().__init__()
        self.d_model = d_model

        encoder_layer = nn.TransformerEncoderLayer(
            d_model         = d_model,
            nhead           = nhead,
            dim_feedforward = dim_ff,
            dropout         = dropout,
            activation      = "gelu",
            batch_first     = True,
            norm_first      = True,    # pre-norm for stability
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
        self._max_len    = max_len

    def _causal_mask(self, T: int, device: torch.device) -> torch.Tensor:
        """Lower-triangular boolean mask: True = ignore (PyTorch convention)."""
        mask = torch.triu(torch.ones(T, T, device=device), diagonal=1).bool()
        return mask

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        x:      (B, T, d_model)
        returns (B, T, d_model)
        """
        T    = x.size(1)
        mask = self._causal_mask(T, x.device)
        return self.transformer(x, mask=mask)


# ══════════════════════════════════════════════════════════════════════════════
#  HULL PREDICTION HEAD
# ══════════════════════════════════════════════════════════════════════════════

class HullPredictionHead(nn.Module):
    """
    Two-head output:
      - prob_head:  sigmoid → P(in_hull | trajectory[:t])
      - logvar_head: log-variance for aleatoric uncertainty (optional)

    Epistemic uncertainty is estimated via MC Dropout (multiple forward passes).
    """

    def __init__(self, d_model: int, dropout: float = 0.1):
        super().__init__()
        self.dropout    = nn.Dropout(dropout)
        self.prob_head  = nn.Sequential(
            nn.Linear(d_model, d_model // 2),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(d_model // 2, 1),
        )

    def forward(self, h: torch.Tensor) -> torch.Tensor:
        """
        h:       (B, T, d_model)
        returns: (B, T)  — sigmoid probabilities
        """
        return torch.sigmoid(self.prob_head(self.dropout(h)).squeeze(-1))


# ══════════════════════════════════════════════════════════════════════════════
#  FULL SEQUENTIAL HULL CLASSIFIER NET
# ══════════════════════════════════════════════════════════════════════════════

class SequentialHullNet(nn.Module):
    """
    Full model: InputEncoder → PE → CausalTransformer → HullHead.
    """

    def __init__(
        self,
        xDim:       int,
        uDim:       int,
        d_model:    int   = 128,
        nhead:      int   = 4,
        num_layers: int   = 3,
        dim_ff:     int   = 256,
        dropout:    float = 0.1,
        max_len:    int   = 1024,
    ):
        super().__init__()
        self.encoder   = TrajectoryInputEncoder(xDim, uDim, d_model)
        self.pe        = SinusoidalPositionalEncoding(d_model, max_len, dropout)
        self.backbone  = CausalTransformerBackbone(d_model, nhead, num_layers,
                                                    dim_ff, dropout, max_len)
        self.head      = HullPredictionHead(d_model, dropout)

    def forward(self, states: torch.Tensor, actions: torch.Tensor) -> torch.Tensor:
        """
        states:  (B, T+1, xDim)
        actions: (B, T,   uDim)
        returns: (B, T)  probabilities
        """
        tokens = self.encoder(states, actions)    # (B, T, d_model)
        tokens = self.pe(tokens)                  # + positional encoding
        hidden = self.backbone(tokens)            # (B, T, d_model)
        return self.head(hidden)                  # (B, T)

    @torch.no_grad()
    def predict_deterministic(self, states: torch.Tensor,
                               actions: torch.Tensor) -> torch.Tensor:
        """Single forward pass, no dropout."""
        self.eval()
        return self(states, actions)

    def predict_with_uncertainty(
        self,
        states:   torch.Tensor,
        actions:  torch.Tensor,
        n_samples: int = 20,
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        MC Dropout uncertainty estimation.
        Keeps model in train() mode to activate dropout at inference.

        Returns:
            mean:  (B, T) — mean predicted probability
            std:   (B, T) — std across MC samples (epistemic uncertainty)
        """
        self.train()    # activates dropout
        samples = torch.stack(
            [self(states, actions) for _ in range(n_samples)], dim=0
        )                                    # (n_samples, B, T)
        mean = samples.mean(dim=0)           # (B, T)
        std  = samples.std(dim=0)            # (B, T)
        return mean, std


# ══════════════════════════════════════════════════════════════════════════════
#  TRAJECTORY LABEL BUFFER
# ══════════════════════════════════════════════════════════════════════════════

@dataclass
class LabeledTrajectory:
    """One labeled episode stored in the training buffer."""
    states:  np.ndarray    # (T+1, xDim)
    actions: np.ndarray    # (T,   uDim)
    labels:  np.ndarray    # (T,)  float in [0, 1]


class TrajectoryLabelBuffer:
    """
    Replay buffer for labeled trajectories.

    Stores full episodes (not individual steps) because the sequence model
    needs the full trajectory context to train correctly.

    Supports:
      - Variable-length trajectories via padding + masking
      - Stratified sampling to balance positive/negative labels
      - Soft labels (from oracle probabilities, not just 0/1)
    """

    def __init__(
        self,
        max_episodes:    int   = 1000,
        max_ep_len:      int   = 512,
        pos_neg_ratio:   float = 0.3,    # target fraction of positive-label steps
    ):
        self.max_episodes  = max_episodes
        self.max_ep_len    = max_ep_len
        self.pos_neg_ratio = pos_neg_ratio
        self._buffer: deque[LabeledTrajectory] = deque(maxlen=max_episodes)

    def push(self, record: EpisodeRecord, labels: np.ndarray):
        """Add a labeled episode. labels: (T,) float."""
        T = min(record.T, self.max_ep_len)
        self._buffer.append(LabeledTrajectory(
            states  = record.states[:T + 1].copy(),
            actions = record.actions[:T].copy(),
            labels  = labels[:T].astype(np.float32),
        ))

    def __len__(self):
        return len(self._buffer)

    def sample_batch(
        self,
        batch_size: int,
        device:     torch.device,
    ) -> Optional[Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]]:
        """
        Sample a padded batch of trajectories.

        Returns:
            states:   (B, T_max+1, xDim)
            actions:  (B, T_max,   uDim)
            labels:   (B, T_max)
            mask:     (B, T_max)  — True = valid step (not padding)
        """
        if len(self._buffer) < batch_size:
            return None

        # Stratified sampling: prefer episodes with at least one positive label
        pos_eps = [e for e in self._buffer if e.labels.max() > 0.5]
        neg_eps = [e for e in self._buffer if e.labels.max() <= 0.5]

        n_pos = max(1, int(batch_size * self.pos_neg_ratio))
        n_neg = batch_size - n_pos

        chosen = []
        if pos_eps:
            idx = np.random.choice(len(pos_eps), min(n_pos, len(pos_eps)), replace=False)
            chosen.extend([pos_eps[i] for i in idx])
        if neg_eps and len(chosen) < batch_size:
            n_neg = batch_size - len(chosen)
            idx   = np.random.choice(len(neg_eps), min(n_neg, len(neg_eps)), replace=False)
            chosen.extend([neg_eps[i] for i in idx])

        if not chosen:
            return None

        # Pad to longest episode in batch
        T_max  = max(e.labels.shape[0] for e in chosen)
        xDim   = chosen[0].states.shape[-1]
        uDim   = chosen[0].actions.shape[-1]
        B      = len(chosen)

        states_arr  = np.zeros((B, T_max + 1, xDim), dtype=np.float32)
        actions_arr = np.zeros((B, T_max,     uDim), dtype=np.float32)
        labels_arr  = np.zeros((B, T_max),           dtype=np.float32)
        mask_arr    = np.zeros((B, T_max),            dtype=bool)

        for i, ep in enumerate(chosen):
            T_i = ep.labels.shape[0]
            states_arr[i,  :T_i + 1, :] = ep.states
            actions_arr[i, :T_i,     :] = ep.actions
            labels_arr[i,  :T_i]        = ep.labels
            mask_arr[i,    :T_i]        = True

        return (
            torch.tensor(states_arr,  device=device),
            torch.tensor(actions_arr, device=device),
            torch.tensor(labels_arr,  device=device),
            torch.tensor(mask_arr,    device=device),
        )

    def positive_fraction(self) -> float:
        """Fraction of steps with positive label across buffer."""
        if not self._buffer:
            return 0.0
        all_labels = np.concatenate([e.labels for e in self._buffer])
        return float(all_labels.mean())


# ══════════════════════════════════════════════════════════════════════════════
#  TRAINING LOOP
# ══════════════════════════════════════════════════════════════════════════════

class HullClassifierTrainer:
    """
    Manages training of SequentialHullNet.

    Loss: weighted BCE to handle class imbalance
          (hull hits are rare → upweight positive labels).

    Also supports soft labels from oracle probabilities.
    """

    def __init__(
        self,
        net:            SequentialHullNet,
        lr:             float = 3e-4,
        weight_decay:   float = 1e-4,
        pos_weight:     float = 5.0,      # upweight positive (in-hull) steps
        warmup_steps:   int   = 200,
        device:         torch.device = torch.device("cpu"),
    ):
        self.net    = net
        self.device = device

        self.optimizer = optim.AdamW(net.parameters(), lr=lr,
                                     weight_decay=weight_decay)
        self.scheduler = optim.lr_scheduler.CosineAnnealingLR(
            self.optimizer, T_max=10000, eta_min=lr * 0.1)

        self._pos_weight  = torch.tensor([pos_weight], device=device)
        self._step        = 0
        self._warmup      = warmup_steps

        self.loss_history: List[float] = []

    def train_epoch(
        self,
        buffer:      TrajectoryLabelBuffer,
        batch_size:  int = 32,
        n_batches:   int = 10,
    ) -> float:
        """Run n_batches gradient steps. Returns mean loss."""
        self.net.train()
        total_loss = 0.0
        count      = 0

        for _ in range(n_batches):
            batch = buffer.sample_batch(batch_size, self.device)
            if batch is None:
                break
            states, actions, labels, mask = batch

            preds = self.net(states, actions)          # (B, T)

            # Masked weighted BCE
            criterion = nn.BCELoss(reduction="none")
            loss_raw  = criterion(preds, labels)       # (B, T)

            # Upweight positive steps
            weights = torch.ones_like(labels)
            weights[labels > 0.5] = self._pos_weight.item()

            loss = (loss_raw * weights * mask.float()).sum() / (mask.float().sum() + 1e-8)

            self.optimizer.zero_grad()
            loss.backward()
            nn.utils.clip_grad_norm_(self.net.parameters(), 1.0)
            self.optimizer.step()

            # Warmup LR
            if self._step < self._warmup:
                for pg in self.optimizer.param_groups:
                    pg["lr"] = pg["lr"] * (self._step + 1) / self._warmup
            else:
                self.scheduler.step()

            self._step    += 1
            total_loss    += loss.item()
            count         += 1

        mean_loss = total_loss / max(count, 1)
        self.loss_history.append(mean_loss)
        return mean_loss

    def compute_metrics(
        self,
        buffer:     TrajectoryLabelBuffer,
        batch_size: int = 64,
        threshold:  float = 0.5,
    ) -> dict:
        """Accuracy, precision, recall on a held-out batch."""
        self.net.eval()
        batch = buffer.sample_batch(batch_size, self.device)
        if batch is None:
            return {}
        states, actions, labels, mask = batch

        with torch.no_grad():
            preds = self.net(states, actions)

        preds_bin = (preds > threshold).float()
        labels_b  = labels

        # Only evaluate on valid (non-padded) steps
        valid     = mask.float()
        tp = ((preds_bin == 1) & (labels_b == 1) & mask).float().sum()
        fp = ((preds_bin == 1) & (labels_b == 0) & mask).float().sum()
        fn = ((preds_bin == 0) & (labels_b == 1) & mask).float().sum()
        tn = ((preds_bin == 0) & (labels_b == 0) & mask).float().sum()

        acc  = (tp + tn) / (valid.sum() + 1e-8)
        prec = tp / (tp + fp + 1e-8)
        rec  = tp / (tp + fn + 1e-8)
        f1   = 2 * prec * rec / (prec + rec + 1e-8)

        return {
            "accuracy":  acc.item(),
            "precision": prec.item(),
            "recall":    rec.item(),
            "f1":        f1.item(),
            "pos_frac":  buffer.positive_fraction(),
        }


# ══════════════════════════════════════════════════════════════════════════════
#  SEQUENTIAL HULL CLASSIFIER MONITOR  (drop-in replacement)
# ══════════════════════════════════════════════════════════════════════════════

class SequentialHullClassifier:
    """
    Drop-in replacement for LearnedHullClassifier using a causal Transformer.

    Pipeline:
      1. Exact oracle runs every `label_every` episodes → labels stored in buffer
      2. Classifier retrains every `train_every` labelings
      3. Between oracle runs → cheap Transformer forward pass
         with MC Dropout uncertainty estimation

    Confidence gating:
      Steps where uncertainty > `uncertainty_threshold` fall back to the
      oracle label (if available) or are marked as uncertain in the result.
    """

    def __init__(
        self,
        xDim:                  int,
        uDim:                  int,
        action_bounds,
        target                 = None,
        # Oracle settings
        oracle_method:         str   = "linprog",
        hull_tolerance:        float = 1e-6,
        label_every:           int   = 10,
        train_every:           int   = 5,
        # Model architecture
        d_model:               int   = 128,
        nhead:                 int   = 4,
        num_layers:            int   = 3,
        dim_ff:                int   = 256,
        dropout:               float = 0.1,
        max_ep_len:            int   = 512,
        # Training
        lr:                    float = 3e-4,
        weight_decay:          float = 1e-4,
        pos_weight:            float = 5.0,
        batch_size:            int   = 32,
        n_batches_per_train:   int   = 20,
        buffer_size:           int   = 1000,
        min_buffer_before_train: int = 20,
        # Inference
        mc_samples:            int   = 20,
        threshold:             float = 0.5,
        uncertainty_threshold: float = 0.2,
        # Device
        device:                str   = "cpu",
    ):
        self.xDim              = xDim
        self.uDim              = uDim
        self.action_bounds     = action_bounds
        self.label_every       = label_every
        self.train_every       = train_every
        self.batch_size        = batch_size
        self.n_batches         = n_batches_per_train
        self.min_buffer        = min_buffer_before_train
        self.mc_samples        = mc_samples
        self.threshold         = threshold
        self.unc_threshold     = uncertainty_threshold
        self.device            = torch.device(device)

        # Oracle (exact hull checker)
        try:
            self._oracle = PostEpisodeHullMonitor(
                xDim=xDim, uDim=uDim, action_bounds=action_bounds,
                target=target, method=oracle_method, hull_tolerance=hull_tolerance,
            )
        except NameError:
            self._oracle = None   # standalone mode — no oracle

        self.target          = (None if target is None
                                else np.asarray(target, dtype=np.float32))
        self.is_valid_target = self.target is not None

        # Sequence model
        self.net = SequentialHullNet(
            xDim=xDim, uDim=uDim,
            d_model=d_model, nhead=nhead,
            num_layers=num_layers, dim_ff=dim_ff,
            dropout=dropout, max_len=max_ep_len + 64,
        ).to(self.device)

        # Label buffer & trainer
        self.buffer  = TrajectoryLabelBuffer(
            max_episodes=buffer_size, max_ep_len=max_ep_len)
        self.trainer = HullClassifierTrainer(
            self.net, lr=lr, weight_decay=weight_decay,
            pos_weight=pos_weight, device=self.device)

        # Counters
        self._ep_count       = 0
        self._label_count    = 0
        self._trained        = False
        self._last_metrics   = {}

    # ── Main entry point ─────────────────────────────────────────────────────

    def process(self, record: EpisodeRecord) -> SequentialHullResult:
        self._ep_count += 1
        run_oracle = (self._ep_count % self.label_every == 0) or not self._trained

        if run_oracle or self._oracle is None:
            return self._process_with_oracle(record)
        else:
            return self._process_with_model(record)

    # ── Oracle path ───────────────────────────────────────────────────────────

    def _process_with_oracle(self, record: EpisodeRecord) -> SequentialHullResult:
        """Run exact hull check, store labels, maybe retrain."""
        oracle_result = self._oracle.process(record) if self._oracle else None

        if oracle_result is not None:
            labels = oracle_result.in_hull_mask.astype(np.float32)
            self.buffer.push(record, labels)
            self._label_count += 1

            # Sync oracle target → our state
            if self._oracle.is_valid_target and not self.is_valid_target:
                self.target          = self._oracle.target
                self.is_valid_target = True

            # Retrain classifier
            if (self._label_count % self.train_every == 0
                    and len(self.buffer) >= self.min_buffer):
                loss = self.trainer.train_epoch(
                    self.buffer, self.batch_size, self.n_batches)
                self._last_metrics = self.trainer.compute_metrics(self.buffer)
                self._last_metrics["train_loss"] = loss
                self._trained = True

            in_hull   = oracle_result.in_hull_mask
            first_hit = oracle_result.first_hull_step
            probs     = labels
            unc       = np.zeros_like(probs)
            source    = "Oracle"
        else:
            # No oracle available — use model or return empty
            return self._process_with_model(record)

        return SequentialHullResult(
            in_hull_mask        = in_hull,
            first_hull_step     = first_hit,
            is_valid_target     = self.is_valid_target,
            source              = source,
            probs               = probs,
            uncertainty         = unc,
            confident_mask      = np.ones(record.T, dtype=bool),
        )

    # ── Model path ────────────────────────────────────────────────────────────

    def _process_with_model(self, record: EpisodeRecord) -> SequentialHullResult:
        """Fast Transformer inference with MC Dropout uncertainty."""
        T       = record.T
        max_len = self.net.pe.pe.shape[1] - 64

        # Truncate if episode is longer than model max_len
        T_eff   = min(T, max_len)
        states  = torch.tensor(
            record.states[:T_eff + 1][np.newaxis], dtype=torch.float32,
            device=self.device)
        actions = torch.tensor(
            record.actions[:T_eff][np.newaxis], dtype=torch.float32,
            device=self.device)

        if self._trained:
            mean, std = self.net.predict_with_uncertainty(
                states, actions, n_samples=self.mc_samples)
            probs = mean.squeeze(0).cpu().numpy()    # (T_eff,)
            unc   = std.squeeze(0).cpu().numpy()     # (T_eff,)
        else:
            # Model not trained yet — return all uncertain
            probs = np.full(T_eff, 0.5, dtype=np.float32)
            unc   = np.full(T_eff, 1.0, dtype=np.float32)

        # Pad back to full T if truncated
        if T_eff < T:
            pad   = T - T_eff
            probs = np.concatenate([probs, np.full(pad, 0.5)])
            unc   = np.concatenate([unc,   np.full(pad, 1.0)])

        in_hull        = probs >= self.threshold
        confident_mask = unc   <= self.unc_threshold
        first_hit      = int(np.argmax(in_hull)) if in_hull.any() else None

        return SequentialHullResult(
            in_hull_mask    = in_hull,
            first_hull_step = first_hit,
            is_valid_target = self.is_valid_target,
            source          = "Transformer",
            probs           = probs,
            uncertainty     = unc,
            confident_mask  = confident_mask,
        )

    # ── Utilities ─────────────────────────────────────────────────────────────

    def get_training_metrics(self) -> dict:
        return self._last_metrics

    def get_model_summary(self) -> dict:
        n_params = sum(p.numel() for p in self.net.parameters())
        return {
            "parameters":    n_params,
            "trained":       self._trained,
            "buffer_size":   len(self.buffer),
            "pos_fraction":  self.buffer.positive_fraction(),
            "oracle_calls":  self._label_count,
            "total_episodes": self._ep_count,
        }

    def save(self, path: str):
        torch.save({
            "net_state":  self.net.state_dict(),
            "target":     self.target,
            "is_valid":   self.is_valid_target,
            "ep_count":   self._ep_count,
            "metrics":    self._last_metrics,
        }, path)
        print(f"[SequentialHullClassifier] Saved to {path}")

    def load(self, path: str):
        ckpt = torch.load(path, map_location=self.device)
        self.net.load_state_dict(ckpt["net_state"])
        self.target          = ckpt.get("target")
        self.is_valid_target = ckpt.get("is_valid", False)
        self._ep_count       = ckpt.get("ep_count", 0)
        self._last_metrics   = ckpt.get("metrics", {})
        self._trained        = True
        self.net.eval()
        print(f"[SequentialHullClassifier] Loaded from {path}")

    def full_reset(self):
        self.target = None
        self.is_valid_target = False
        self._trained = False
        self._ep_count = self._label_count = 0
        self.buffer = TrajectoryLabelBuffer()
        if self._oracle:
            self._oracle.full_reset()
        # Re-initialize network weights
        self.net.apply(lambda m: m.reset_parameters()
                        if hasattr(m, "reset_parameters") else None)


# ══════════════════════════════════════════════════════════════════════════════
#  QUICK DEMO
# ══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    import time

    xDim          = 4
    uDim          = 2
    action_bounds = ([-1] * uDim, [1] * uDim)
    T             = 80

    def make_record(ep_id=0):
        return EpisodeRecord(
            states  = np.random.randn(T + 1, xDim).astype(np.float32),
            actions = np.random.randn(T,     uDim).astype(np.float32),
            rewards = np.random.randn(T).astype(np.float32),
            ep_id   = ep_id,
        )

    monitor = SequentialHullClassifier(
        xDim=xDim, uDim=uDim,
        action_bounds=action_bounds,
        label_every=3,
        train_every=2,
        d_model=64, nhead=4, num_layers=2, dim_ff=128,
        mc_samples=10,
        min_buffer_before_train=2,
        device="cpu",
    )

    print("Running 20 episodes...")
    for i in range(20):
        t0  = time.time()
        rec = make_record(ep_id=i)
        r   = monitor.process(rec)
        dt  = time.time() - t0
        print(f"  ep={i:>3} | source={r.source:<15} | "
              f"hit={str(r.hull_reached):<5} | "
              f"mean_prob={r.probs.mean():.3f} | "
              f"mean_unc={r.uncertainty.mean():.3f} | "
              f"dt={dt*1000:.1f}ms")

    print("\nModel summary:")
    for k, v in monitor.get_model_summary().items():
        print(f"  {k}: {v}")

    print("\nTraining metrics:")
    for k, v in monitor.get_training_metrics().items():
        print(f"  {k}: {v:.4f}" if isinstance(v, float) else f"  {k}: {v}")
